development:
  adapter: mysql2
  database: squidtree
  encoding: utf8
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  database: squidtree
  encoding: utf8
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  database: squidtree
  encoding: utf8
  username: root
  password: root
  host: localhost